name: Build and Release Zap

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release (e.g., 1.0.0)'
        required: true
    
      pastebin_id:
        description: 'Pastebin ID for the release description'
        required: true
jobs:
  build:
    name: Build Zap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.7

      - name: Build binary
        run: |
          go mod init github.com/SublimateTheBerry/zap
          go build -o zap

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap
          path: zap

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: zap

      - name: Get release description from Pastebin
        id: get_description
        run: |
          DESCRIPTION=$(curl -s "https://pastebin.com/raw/${{ github.event.inputs.pastebin_id }}")
          echo "description=$DESCRIPTION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ env.description }}
          files: zap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
